In [ ]:
from konlpy.tag import Okt

okt = Okt() # 형태소 분석기 객체 생성
noun_list = []
for content in tqdm(df['content']): 
    nouns = okt.nouns(content) # 명사만 추출하기, 결과값은 명사 리스트
    noun_list.append(nouns)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/honey/data/portal_news.csv")
data.head()

,Unnamed: 0,link,body,reporter,title,date,news
0,0,https://n.news.naver.com/article/025/000325515...,김정은 북한 국무위원장이 과거 도널드 트럼프 미국 전 대통령이 그에게 붙인 별명 ‘...,배재성 기자,"“김정은, 트럼프에 ‘로켓맨’은 OK, ‘리틀’은 NO”",2023-01-24 23:01:00,중앙일보
1,1,https://n.news.naver.com/article/025/000325514...,북한이 지난해 신종 코로나바이러스 감염증(코로나19) 극복 성과를 선전하는 다큐멘터...,배재성 기자,"북한, 코로나19 극복 다큐 방영…“80여일만 종식 기적”",2023-01-24 21:39:00,중앙일보
2,2,https://n.news.naver.com/article/025/000325514...,북한 매체가 윤석열 대통령의 아랍에미리트(UAE) 방문 당시 발언을 비난하고 나섰다...,하수영 기자,"北매체, 尹 'UAE 적은 이란' 발언 비난 ""해당 나라 분노했다""",2023-01-24 19:49:00,중앙일보
3,3,https://n.news.naver.com/article/025/000325514...,국민의힘 당권주자로 거론되는 나경원 전 의원이 24일 3·8 국민의힘 전당대회 출...,배재성 기자,"나경원, 내일 전대 출마 여부 입장 발표…“결심 섰다”",2023-01-24 19:17:00,중앙일보
4,4,https://n.news.naver.com/article/025/000325514...,28일로 예정된 검찰 출석을 앞두고 이재명 민주당 대표는 설 연휴 기간(21~24일...,성지원 기자,"檢 출석 앞둔 이재명, '처럼회'와 회동…비명계는 별도 모임 발족",2023-01-24 18:58:00,중앙일보

# 1차 시도

In [ ]:
pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 61.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.8/dist-packages (from konlpy) (1.21.6)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.8/dist-packages (from konlpy) (4.9.2)
Collecting JPype1>=0.7.0
  Downloading JPype1-1.4.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (465 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 33.0 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from JPype1>=0.7.0->konlpy) (23.0)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.1 konlpy-0.6.0

In [ ]:
from konlpy.tag import Okt

okt = Okt() # 형태소 분석기 객체 생성
noun_list = []
for content in data['body']: 
    nouns = okt.nouns(content) # 명사만 추출하기, 결과값은 명사 리스트
    noun_list.append(nouns)

In [ ]:
data['nouns'] = noun_list

In [ ]:
data.head()

,Unnamed: 0,link,body,reporter,title,date,news,nouns
0,0,https://n.news.naver.com/article/025/000325515...,김정은 북한 국무위원장이 과거 도널드 트럼프 미국 전 대통령이 그에게 붙인 별명 ‘...,배재성 기자,"“김정은, 트럼프에 ‘로켓맨’은 OK, ‘리틀’은 NO”",2023-01-24 23:01:00,중앙일보,"[김정은, 북한, 국무위원, 과거, 도널드, 트럼프, 미국, 전, 대통령, 그, 별..."
1,1,https://n.news.naver.com/article/025/000325514...,북한이 지난해 신종 코로나바이러스 감염증(코로나19) 극복 성과를 선전하는 다큐멘터...,배재성 기자,"북한, 코로나19 극복 다큐 방영…“80여일만 종식 기적”",2023-01-24 21:39:00,중앙일보,"[북한, 지난해, 신종, 코로나바이러스, 감염증, 코로나, 극복, 성과, 선전, 다..."
2,2,https://n.news.naver.com/article/025/000325514...,북한 매체가 윤석열 대통령의 아랍에미리트(UAE) 방문 당시 발언을 비난하고 나섰다...,하수영 기자,"北매체, 尹 'UAE 적은 이란' 발언 비난 ""해당 나라 분노했다""",2023-01-24 19:49:00,중앙일보,"[북한, 매체, 윤석열, 대통령, 아랍에미리트, 방문, 당시, 발언, 비난, 북한,..."
3,3,https://n.news.naver.com/article/025/000325514...,국민의힘 당권주자로 거론되는 나경원 전 의원이 24일 3·8 국민의힘 전당대회 출...,배재성 기자,"나경원, 내일 전대 출마 여부 입장 발표…“결심 섰다”",2023-01-24 19:17:00,중앙일보,"[국민, 힘, 당권, 주자, 거론, 나경원, 전, 의원, 국민, 힘, 전당대회, 출..."
4,4,https://n.news.naver.com/article/025/000325514...,28일로 예정된 검찰 출석을 앞두고 이재명 민주당 대표는 설 연휴 기간(21~24일...,성지원 기자,"檢 출석 앞둔 이재명, '처럼회'와 회동…비명계는 별도 모임 발족",2023-01-24 18:58:00,중앙일보,"[예정, 검찰, 출석, 이재명, 민주당, 대표, 설, 연휴, 기간, 공개, 행보, ..."

In [ ]:
drop_index_list = [] # 지워버릴 index를 담는 리스트
for i, row in data.iterrows():
    temp_nouns = row['nouns']
    if len(temp_nouns) == 0: # 만약 명사리스트가 비어 있다면
        drop_index_list.append(i) # 지울 index 추가
        
df = data.drop(drop_index_list) # 해당 index를 지우기

# index를 지우면 순회시 index 값이 중간중간 비기 때문에 index를 다시 지정
df.index = range(len(df))

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 문서를 명사 집합으로 보고 문서 리스트로 치환 (tfidfVectorizer 인풋 형태를 맞추기 위해)
text = [" ".join(noun) for noun in df['nouns']]

tfidf_vectorizer = TfidfVectorizer(min_df = 5, ngram_range=(1,5))
tfidf_vectorizer.fit(text)
vector = tfidf_vectorizer.transform(text).toarray()

In [ ]:
from sklearn.cluster import DBSCAN
import numpy as np

vector = np.array(vector) # Normalizer를 이용해 변환된 벡터
model = DBSCAN(eps=0.3,min_samples=6, metric = "cosine")
# 거리 계산 식으로는 Cosine distance를 이용
result = model.fit_predict(vector)

In [ ]:
result

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
data['result'] = result

In [ ]:
for cluster_num in set(result):
    # -1,0은 노이즈 판별이 났거나 클러스터링이 안된 경우
    if(cluster_num == -1 or cluster_num == 0): 
        continue
    else:
        print("cluster num : {}".format(cluster_num))
        temp_df = data[data['result'] == cluster_num] # cluster num 별로 조회
        for title in temp_df['title']:
            print(title) # 제목으로 살펴보자
        print()

# 2차 시도

In [ ]:
import pandas as pd
import konlpy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import AgglomerativeClustering

In [ ]:
df2 = data
df2.head()

,Unnamed: 0,link,body,reporter,title,date,news
0,0,https://n.news.naver.com/article/025/000325515...,김정은 북한 국무위원장이 과거 도널드 트럼프 미국 전 대통령이 그에게 붙인 별명 ‘...,배재성 기자,"“김정은, 트럼프에 ‘로켓맨’은 OK, ‘리틀’은 NO”",2023-01-24 23:01:00,중앙일보
1,1,https://n.news.naver.com/article/025/000325514...,북한이 지난해 신종 코로나바이러스 감염증(코로나19) 극복 성과를 선전하는 다큐멘터...,배재성 기자,"북한, 코로나19 극복 다큐 방영…“80여일만 종식 기적”",2023-01-24 21:39:00,중앙일보
2,2,https://n.news.naver.com/article/025/000325514...,북한 매체가 윤석열 대통령의 아랍에미리트(UAE) 방문 당시 발언을 비난하고 나섰다...,하수영 기자,"北매체, 尹 'UAE 적은 이란' 발언 비난 ""해당 나라 분노했다""",2023-01-24 19:49:00,중앙일보
3,3,https://n.news.naver.com/article/025/000325514...,국민의힘 당권주자로 거론되는 나경원 전 의원이 24일 3·8 국민의힘 전당대회 출...,배재성 기자,"나경원, 내일 전대 출마 여부 입장 발표…“결심 섰다”",2023-01-24 19:17:00,중앙일보
4,4,https://n.news.naver.com/article/025/000325514...,28일로 예정된 검찰 출석을 앞두고 이재명 민주당 대표는 설 연휴 기간(21~24일...,성지원 기자,"檢 출석 앞둔 이재명, '처럼회'와 회동…비명계는 별도 모임 발족",2023-01-24 18:58:00,중앙일보

In [ ]:
documents_processed = []

for text in df2['body']:
    okt = konlpy.tag.Okt() 
    okt_pos = okt.pos(text)

    words = []
    for word, pos in okt_pos:
        if 'Noun' in pos:
            words.append(word)

    documents_processed.append(' '.join(words))

print(len(documents_processed))
documents_processed[0]

400

'김정은 북한 국무위원 과거 도널드 트럼프 미국 전 대통령 그 별명 리틀 로켓 맨 로켓 맨 리틀 안 고 언급 마이크 폼페이 오 전 국무장관 전 현지 시간 비즈니스 사이더 마이크 폼페이 오 전 장관 회고록 치도 내 사랑 미국 위 싸움 일화 전 폼페이 오 전 장관 책 싱가포르 북미 정상회담 오찬 대화 당시 트럼프 전 대통령 김 위원장 엘턴 존 고 그 히트 곡 로켓 맨 별명 설명 폼페이 트럼프 전 대통령 이 곡 로켓 맨 노래 그 표현 칭찬 것 말 고 회고록 회고록 트럼프 전 대통령 설명 김 위원장 비롯 참석자 대부분 웃음 김 위원장 로켓 맨 리틀 은 안 고 농담 폼페이 오 전 장관 회고 폼페이 또 나 북한 친구 김정은 통굽 신발 것 바로 그 트럼프 대통령 피트 약 며 피트 인치 정도 김 위원장 말 그대로 인치 양보 수 고 트럼프 전 대통령 트위터 김 위원장 리틀 로켓 맨 처음 언급 대통령 재임 기간 유엔 총회 연설 등 여러 공식 석상 이 표현 사용'

In [ ]:
tfidf_vectorizer = TfidfVectorizer(min_df=1, ngram_range=(1,1))

tfidf_vector = tfidf_vectorizer.fit_transform(documents_processed)

tfidf_dense = tfidf_vector.todense()

In [ ]:
model = AgglomerativeClustering(linkage='complete', affinity='cosine', n_clusters=4)
model.fit(tfidf_dense)
model.labels_

array([0, 2, 0, 1, 0, 1, 3, 1, 3, 1, 1, 1, 3, 2, 0, 2, 1, 1, 1, 2, 1, 3,
       0, 3, 0, 1, 1, 0, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 3, 1, 1, 2, 0,
       3, 3, 2, 0, 3, 1, 3, 1, 3, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0,
       0, 3, 2, 1, 2, 3, 3, 1, 1, 0, 3, 0, 3, 2, 1, 0, 0, 1, 1, 1, 3, 3,
       0, 2, 1, 0, 3, 0, 1, 0, 0, 1, 0, 2, 1, 3, 2, 1, 2, 0, 1, 3, 0, 1,
       0, 2, 1, 2, 2, 0, 1, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 3, 2, 1, 1, 1,
       3, 1, 2, 3, 1, 3, 0, 3, 3, 3, 1, 1, 1, 0, 0, 0, 3, 1, 3, 3, 2, 3,
       3, 1, 3, 3, 0, 3, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 1, 0, 1, 3, 3,
       1, 2, 1, 0, 0, 3, 3, 1, 1, 0, 3, 3, 2, 1, 2, 2, 1, 1, 1, 3, 1, 0,
       0, 0, 1, 1, 1, 1, 3, 0, 1, 0, 1, 2, 0, 3, 2, 2, 1, 2, 1, 1, 3, 0,
       0, 1, 2, 1, 3, 1, 0, 0, 0, 1, 1, 0, 0, 1, 3, 0, 3, 1, 0, 1, 0, 1,
       2, 3, 1, 3, 3, 0, 1, 3, 3, 1, 1, 0, 1, 0, 1, 0, 2, 3, 0, 2, 0, 1,
       3, 0, 0, 0, 3, 0, 2, 2, 1, 3, 0, 1, 3, 2, 0, 0, 2, 0, 0, 2, 3, 0,
       0, 0, 3, 1, 0, 1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 2, 3, 1, 2, 0,
       1, 1, 1, 3, 0, 1, 1, 0, 1, 1, 3, 1, 0, 2, 1, 1, 1, 1, 1, 3, 1, 0,
       0, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 3, 2, 1, 0, 1, 0, 1, 3, 1,
       3, 1, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1, 1, 1, 3, 1, 1, 3, 0, 2, 1, 1,
       1, 1, 0, 1, 1, 2, 3, 0, 1, 1, 1, 0, 1, 3, 1, 1, 1, 1, 1, 2, 1, 0,
       0, 1, 2, 3])

In [ ]:
cluster_df = pd.DataFrame(zip(df2['title'], model.labels_), columns=['title', 'cluster'])
cluster_df.head()

                                   title  cluster
0        “김정은, 트럼프에 ‘로켓맨’은 OK, ‘리틀’은 NO”        0
1       북한, 코로나19 극복 다큐 방영…“80여일만 종식 기적”        2
2  北매체, 尹 'UAE 적은 이란' 발언 비난 "해당 나라 분노했다"        0
3         나경원, 내일 전대 출마 여부 입장 발표…“결심 섰다”        1
4   檢 출석 앞둔 이재명, '처럼회'와 회동…비명계는 별도 모임 발족        0

In [ ]:
data['cluster'] = model.labels_

In [ ]:
data.head()

,Unnamed: 0,link,body,reporter,title,date,news,cluster
0,0,https://n.news.naver.com/article/025/000325515...,김정은 북한 국무위원장이 과거 도널드 트럼프 미국 전 대통령이 그에게 붙인 별명 ‘...,배재성 기자,"“김정은, 트럼프에 ‘로켓맨’은 OK, ‘리틀’은 NO”",2023-01-24 23:01:00,중앙일보,0
1,1,https://n.news.naver.com/article/025/000325514...,북한이 지난해 신종 코로나바이러스 감염증(코로나19) 극복 성과를 선전하는 다큐멘터...,배재성 기자,"북한, 코로나19 극복 다큐 방영…“80여일만 종식 기적”",2023-01-24 21:39:00,중앙일보,2
2,2,https://n.news.naver.com/article/025/000325514...,북한 매체가 윤석열 대통령의 아랍에미리트(UAE) 방문 당시 발언을 비난하고 나섰다...,하수영 기자,"北매체, 尹 'UAE 적은 이란' 발언 비난 ""해당 나라 분노했다""",2023-01-24 19:49:00,중앙일보,0
3,3,https://n.news.naver.com/article/025/000325514...,국민의힘 당권주자로 거론되는 나경원 전 의원이 24일 3·8 국민의힘 전당대회 출...,배재성 기자,"나경원, 내일 전대 출마 여부 입장 발표…“결심 섰다”",2023-01-24 19:17:00,중앙일보,1
4,4,https://n.news.naver.com/article/025/000325514...,28일로 예정된 검찰 출석을 앞두고 이재명 민주당 대표는 설 연휴 기간(21~24일...,성지원 기자,"檢 출석 앞둔 이재명, '처럼회'와 회동…비명계는 별도 모임 발족",2023-01-24 18:58:00,중앙일보,0

In [ ]:
data.to_csv('cluster.csv', sep=',', encoding='utf-8')